default:
	@just -l

	python3.12 -m venv .venv
	python -m pip install --upgrade pip
	pip install uv

migrate:
	@python manage.py migrate

makemigrations:
	@python manage.py makemigrations


createsuperuser:
	python manage.py  createsuperuser --username admin --email admin@via-internet.de
	
run:
	@python manage.py runserver

