# Generated by Django 4.2 on 2026-01-14 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_farmer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilrecord',
            name='farmers_id',
            field=models.ForeignKey(db_column='farmers_id', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='soil_records_by_farmers_id', to='App.farmer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='soilrecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
