# Generated by Django 4.2 on 2026-01-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_soilrecord_farmers_id_alter_soilrecord_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilrecord',
            name='farmers_id',
        ),
    ]
