# Generated by Django 4.2 on 2026-01-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_soilrecord_farmers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croprecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='waterrecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
