# Generated by Django 4.2 on 2026-01-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
